# Generated by Django 6.1 on 2026-08-24 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_banner_alter_product_options_reelsvideo_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reelsvideo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='reelsvideo',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='reelsvideo',
            name='video_file',
        ),
        migrations.AddField(
            model_name='reelsvideo',
            name='video',
            field=models.FileField(default=1, upload_to='reels/videos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reelsvideo',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reelsvideo',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reels', to='store.product'),
        ),
        migrations.AlterField(
            model_name='reelsvideo',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
