# Generated by Django 6.1 on 2026-08-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_review_options_alter_review_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Promokod')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='Chegirma foizi (%)')),
                ('active', models.BooleanField(default=True, verbose_name='Faolligi')),
                ('valid_from', models.DateTimeField(verbose_name='Boshlanish vaqti')),
                ('valid_to', models.DateTimeField(verbose_name='Tugash vaqti')),
            ],
            options={
                'verbose_name': 'Promokod',
                'verbose_name_plural': 'Promokodlar',
            },
        ),
    ]
