# Generated by Django 6.1 on 2026-08-29 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Buyurtma qabul qilindi'), ('processing', 'Tayyorlanmoqda'), ('shipped', 'Yetkazib berishga chiqarildi'), ('delivered', 'Yetkazib berildi'), ('cancelled', 'Bekor qilindi')], max_length=20, verbose_name='Status')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="O'zgartirilgan vaqti")),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='store.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Buyurtma tarixi',
                'verbose_name_plural': 'Buyurtma tarixi',
                'ordering': ['-created_at'],
            },
        ),
    ]
