# Generated by Django 6.1 on 2026-08-29 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_orderstatushistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reelsvideo',
            name='product',
        ),
        migrations.AddField(
            model_name='reelsvideo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='reelsvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='reels/thumbnails/', verbose_name='Muqova (Thumbnail)'),
        ),
        migrations.AlterField(
            model_name='reelsvideo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti"),
        ),
        migrations.AlterField(
            model_name='reelsvideo',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Tasdiqlangan'),
        ),
        migrations.AlterField(
            model_name='reelsvideo',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='reelsvideo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='reelsvideo',
            name='video',
            field=models.FileField(upload_to='reels/videos/', verbose_name='Video fayl'),
        ),
        migrations.AlterField(
            model_name='reelsvideo',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni"),
        ),
    ]
