# Generated by Django 6.1 on 2026-08-29 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_reelsvideo_product_reelsvideo_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reelsvideo',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reels', to='store.product', verbose_name="Bog'langan mahsulot"),
        ),
    ]
