# Generated by Django 6.1 on 2026-08-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_reelsvideo_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='reelsvideo',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Narxi'),
        ),
    ]
